/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CrearMaquina.java
 *
 * Created on 25/09/2010, 06:36:32 PM
 */

package vista;

import Modelo.Cadena;
import Modelo.Cinta;
import Modelo.Estado;
import Modelo.Simbolo;
import java.util.Iterator;
import java.util.ListIterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Benlly
 */
public class CrearMaquina extends javax.swing.JDialog {


    MaquinaTuring parent;
    Cadena cadena = null;
    /** Creates new form CrearMaquina */
    public CrearMaquina(MaquinaTuring parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        load();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Cadena = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Maquina");

        jTable_Cadena.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Caracter"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Cadena);

        jLabel2.setText("Lista de Simbolos en la Nueva Cinta");

        jLabel1.setText("Cadena de Simbolos");

        jButton1.setText("Crear Cinta de la Maquina");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCintaDeLaMaquina(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar(evt);
            }
        });

        jLabel3.setText("Ingrese Los caracteres de la nueva cinta");

        jLabel4.setText("Estado Inicial");

        jButton3.setText("Reset");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetCadena(evt);
            }
        });

        jLabel5.setText("Seleccione un estado inicial.");

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addGap(207, 207, 207))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, 0, 73, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(62, 62, 62)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(130, 130, 130))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(87, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton1)
                    .addContainerGap(325, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearCintaDeLaMaquina(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCintaDeLaMaquina
        String cadenaTexto = jTextField1.getText().trim();
        if(cadenaTexto.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "ingrese la cadena a ser comprovada", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        cadena = new Cadena();


        //simbolo "#" inicial
        cadena.agregarSimbolo(parent.getAdministrador(),"#");
        

        for(int i = 0; i <cadenaTexto.length(); i++){
            System.out.println(cadenaTexto.substring(i, i+1));
            if(parent.getAdministrador().getSimbolo(cadenaTexto.substring(i, i+1)) == null){
                JOptionPane.showMessageDialog(this, "el carcater \""+cadenaTexto.substring(i, i+1)+"\" no se encuentra en la lista de simbolos", "Error", JOptionPane.ERROR_MESSAGE);
                cadena.resetAll(parent.getAdministrador());
                return;
            }else{
                cadena.agregarSimbolo(parent.getAdministrador(), cadenaTexto.substring(i, i+1));
            }
        }


        //simbolo "#" final
        cadena.agregarSimbolo(parent.getAdministrador(),"#");


        parent.setCinta(new Cinta(cadena));
        JOptionPane.showMessageDialog(this, "Todos los caracteres han sido agregados", "Crear Maquina", JOptionPane.INFORMATION_MESSAGE);
        cargarSimbolos();
        jButton1.setEnabled(false);
        jButton3.setEnabled(true);
    }//GEN-LAST:event_crearCintaDeLaMaquina

    private void resetCadena(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetCadena
        // TODO add your handling code here:
        cadena.resetAll(parent.getAdministrador());
        jButton1.setEnabled(true);
        jButton3.setEnabled(false);
    }//GEN-LAST:event_resetCadena

    private void aceptar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar
        Modelo.Estado estadoInicial = parent.getConjuntoEstados().getEstado((String)jComboBox1.getSelectedItem());
        parent.getUnidad().setStateInicial(estadoInicial);
        dispose();
    }//GEN-LAST:event_aceptar

    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        dispose();
    }//GEN-LAST:event_cancelar

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Cadena;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void load() {

        Iterator i = parent.getConjuntoEstados().getListEstados().iterator();
        while(i.hasNext()){
            jComboBox1.addItem(((Estado)i.next()).getnombre());
        }

        if(parent.getCinta()!= null && parent.getCinta().getCadena()!=null){
               this.cadena = parent.getCinta().getCadena();
               jTextField1.setText(parent.getCinta().getCadenaActual());
               cargarSimbolos();
               jButton1.setEnabled(false);
               jButton3.setEnabled(true);
        }
    }

    private void cargarSimbolos() {
        ListIterator<Simbolo> i = parent.getCinta().getCadena().getListaSimbolos().listIterator();
        borrarTodasLasFilas((DefaultTableModel)jTable_Cadena.getModel());
        while(i.hasNext()){
            Simbolo actual = (Simbolo)i.next();
            ((DefaultTableModel)jTable_Cadena.getModel()).addRow(new Object[]{i.nextIndex(),actual.getsimbolo()});
        }
    }

    public void borrarTodasLasFilas(DefaultTableModel dtm){
        for (int i = dtm.getRowCount() -1; i >= 0; i--){
            dtm.removeRow(i);
        }
    }

}
